version: "3"

tasks:
  check:
    desc: Check the code
    cmds:
      - task: prettier
        vars:
          PRETTIER_ARGS: --check
      - npx tsc

  test:
    desc: Run the tests
    cmds:
      - echo "No tests"

  fix:
    desc: Fix the code
    cmds:
      - task: prettier
        vars:
          PRETTIER_ARGS: --write

  prettier:
    vars:
      PRETTIER_CONFIG: >
        --tab-width 4
        --end-of-line auto
    cmds:
    - npx prettier . {{.PRETTIER_ARGS}} {{.PRETTIER_CONFIG}}
