version: "3"

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

tasks:
  install:
    - pnpm install
    - task: ecma:config
  upgrade:
    - pnpm up mono-dev
    - pnpm dedupe
    - pnpm dedupe --check
    - task: install

  check:
    - task: ecma:check
  fix:
    - task: ecma:fix
  test:
    - task: ecma:test
  dev:
    - task: ecma:test-dev
  build:
    - task: ecma:lib-build

  doc:
    - task: ecma:doc-build
  dev-doc:
    - task: ecma:doc-dev
  
  publish:
    - rm -rf dist
    - task: install
    - task: check
    - task: test
    - task: build
    - task: doc
    - pnpm publish --access public

