version: "3"

tasks:
  check:
    desc: Check the code
    cmds:
      - task: prettier
        vars:
          PRETTIER_ARGS: --check
      - npx tsc

  test:
    desc: Run the tests
    cmds:
      - npx -w packages/pure vitest run

  fix:
    desc: Fix the code
    cmds:
      - task: prettier
        vars:
          PRETTIER_ARGS: --write

  prettier:
    vars:
      PRETTIER_CONFIG: >
        --tab-width 4
        --end-of-line auto
    cmds:
      - npx prettier . {{.PRETTIER_ARGS}} {{.PRETTIER_CONFIG}}

  doc:
    desc: Generate the documentation
    cmds:
      - npx typedoc

  serve:
    desc: Serve the documentation
    cmds:
      - npx serve docs

  publish:
    cmds:
      - npm publish -w packages/{{.CLI_ARGS}} --access public
