version: "3"

includes:
  common:
    taskfile: ./packages/mono-dev/task/common.yaml
    flatten: true
    optional: true

  pure:
    aliases: [p]
    taskfile: ./packages/pure
    dir: ./packages/pure
    internal: true

  pure-react:
    aliases: [pr]
    taskfile: ./packages/pure-react
    dir: ./packages/pure-react
    internal: true

  pure-i18next:
    aliases: [pi]
    taskfile: ./packages/pure-i18next
    dir: ./packages/pure-i18next
    internal: true

tasks:
  install:
    cmds:
      - pnpm install

  check:
    desc: Check the code
    deps:
      - pure:check
      - pure-react:check
      - pure-i18next:check

  test:
    desc: Run the tests
    cmds:
      - task: pure:test

  fix:
    desc: Fix the code
    deps:
      - pure:fix
      - pure-react:fix
      - pure-i18next:fix

  doc:
    desc: Generate the documentation
    deps:
      - pure:install
      - pure-react:install
      - pure-i18next:install
    cmds:
      - pnpm exec typedoc

  serve:
    desc: Serve the documentation
    cmds:
      - pnpm exec serve docs

  publish:
    deps: [check, test, doc]
    cmds:
      - pnpm -r publish --access public
