version: "3"

includes:
  react:
    taskfile: ./react
    dir: ./react

tasks:
  check:
    desc: Check the code
    cmds:
      - task: prettier
        vars:
          PRETTIER_ARGS: --check
      - npx tsc
      - deno lint
      - npx jsr publish --dry-run

  test:
    desc: Run the tests
    cmds:
      - echo "No tests"

  fix:
    desc: Fix the code
    cmds:
      - deno lint --fix
      - task: prettier
        vars:
          PRETTIER_ARGS: --write

  prettier:
    cmds:
    - npx prettier "./**/*.{ts,tsx,json,jsonc,js,jsx,cjs}" {{.PRETTIER_ARGS}}

  publish:
    desc: Publish the package
    cmds:
      - npx jsr publish
