version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix

  test:
    cmds:
      - task: ecma:vitest

  dev:
    cmds:
      - task: ecma:vitest-watch
